### ISSUE TITLE
:D

### ISSUE THREAD

**Issue by liberodark** [theo546/stuff#1]
Y a pas à dire c'est un top projet j'aime bien les commits aussi ^^
Au faite j'aurais besoin de toi d'ailleurs à l’occasion voici mon discord
liberodark#0928 (si tu la plus)

**Comment by theo546** [comment]
Non merci. Si t'a oublié mon pseudo Discord (sachant que je t'ai toujours dans ma liste d'amis), c'est qu'il y a un problème.
